// Code generated by bpmn2go; DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// ProcessTask is the activity completion receipt. Retries share a logical task key.
type ProcessTask struct{ ent.Schema }

func (ProcessTask) Mixin() []ent.Mixin { return []ent.Mixin{IdentityMixin{}} }
func (ProcessTask) Fields() []ent.Field {
	return []ent.Field{
		field.String("workflow_id").Immutable(),
		field.String("run_id").Immutable(),
		field.Enum("task_id").Values("pack_express", "pack_standard", "pick_01", "pick_02", "pick_03", "pick_04", "pick_05", "pick_06", "pick_07", "pick_08").Immutable(),
		field.String("aisle").Immutable(),
	}
}
func (ProcessTask) Indexes() []ent.Index {
	return []ent.Index{index.Fields("tenant_id", "workflow_id", "run_id", "task_id").Unique()}
}
